name: isbndb
description: Dart service for isbndb.com API. Returns book details from an ISBN, or a list of books from an author name, etc.
version: 0.3.0
repository: https://github.com/julienlebren/flutter_ISBNdb
issue_tracker: https://github.com/julienlebren/flutter_ISBNdb/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  freezed: ^2.4.2
  json_serializable: ^6.1.5

flutter:
