name: isbndb
description: Dart service for isbndb.com API. Returns book details from an ISBN, or a list of books from an author name, etc.
version: 0.2.7
repository: https://github.com/julienlebren/flutter_ISBNdb
issue_tracker: https://github.com/julienlebren/flutter_ISBNdb/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter  
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  